name: tii-rplidar-ros2-coverity

on:
  workflow_dispatch:
  push:
    branches:
      - new_ros2
  pull_request:
    branches:
      - new_ros2

jobs:
  coverity:
    runs-on: rplidar-ros2-self-hosted-coverity
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run coverity scan
        run: |
          docker run --rm \
            -e PROJECT_NAME=${{ github.event.repository.name }} \
            -v "$(pwd):/main_ws/src" \
            ghcr.io/tiiuae/fog-ros-baseimage-builder-coverity:sha-4da4f0d
      - name: Update summary
        run: |
          cat cov-analyze-result.txt >> $GITHUB_STEP_SUMMARY
      - name: Upload coverity scan results
        uses: actions/upload-artifact@v4
        with:
          name: coverity-html-report-${{ github.event.repository.name }}
          path: coverity-output
